---
title: "Meta-analysis of Toy Preference Studies"
author: "Chen Ye"
date: today
format:  
  html:
    theme: lumen
    toc: true
    toc_float: true
title-block-banner: true
execute:
  echo: fenced
---

```{r}
#| label = "setup"
#| include = FALSE

# 
library(meta)
library(metafor)
library(dplyr)
library(readxl)

# ）
# setwd("your/working/directory")

# Loading Data
data <- read_excel("data/metaanalysis_data.xlsx", sheet = "Arkusz2" ) 
colnames(Meta_Analysis_Data)
```

```{r}
compute_effects <- function(n1, m1, sd1, n2, m2, sd2) {
  pooled_sd <- sqrt(((n1 - 1)*sd1^2 + (n2 - 1)*sd2^2) / (n1 + n2 - 2))
  d <- (m1 - m2) / pooled_sd
  se_d <- sqrt((n1 + n2) / (n1 * n2) + (d^2) / (2 * (n1 + n2)))
  return(data.frame(d = d, se_d = se_d))
}

effects <- mapply(compute_effects,
                  data$N_boys,
                  data$Mean_boys_play_male,
                  data$SD_boys_play_male,
                  data$N_girls,
                  data$Mean_girls_play_male,
                  data$SD_girls_play_male,
                  SIMPLIFY = FALSE)

effects_df <- do.call(rbind, effects)
data$d <- effects_df$d
data$se_d <- effects_df$se_d

res <- rma(yi = d, sei = se_d, data = data, method = "REML")  
summary(res)


funnel(res)


```

```{r}


# The impact of quality rating on effect size
res_quality <- rma(yi = TE, sei = seTE, mods = ~ RoB, data = Meta_Analysis_Data)
summary(res_quality)

preds <- predict(res_quality, newmods = Meta_Analysis_Data$RoB)


plot(Meta_Analysis_Data$RoB, Meta_Analysis_Data$TE,
     xlab = "Risk of Bias Score",
     ylab = "Effect Size (TE)",
     main = "Meta-regression: RoB vs TE")


lines(Meta_Analysis_Data$RoB, preds$pred, col = "blue", lwd = 2)


```

```{r}
grep("female", colnames(Meta_Analysis_Data), ignore.case=TRUE, value=TRUE)
grep("male", colnames(Meta_Analysis_Data), ignore.case=TRUE, value=TRUE)
colnames(Meta_Analysis_Data)
table(Meta_Analysis_Data$AuthorGender)

t.test(TE ~ AuthorGender, data = Meta_Analysis_Data)
boxplot(TE ~ AuthorGender, data = Meta_Analysis_Data,
        names = c("Male authors", "Female authors"),
        main = "Effect Size (TE) by Author Gender",
        ylab = "TE")



```



